"""alter user columns

Revision ID: 159d0b760f64
Revises: d5b00d4e79b5
Create Date: 2025-11-11 10:06:55.164984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '159d0b760f64'
down_revision = 'd5b00d4e79b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_column('resend_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resend_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='how many time otp sent'))

    # ### end Alembic commands ###
