"""add forgot password table

Revision ID: 29a589d50ab3
Revises: 4ab06e515c22
Create Date: 2025-12-02 10:53:34.539720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29a589d50ab3'
down_revision = '4ab06e515c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forgot_password', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='store jwt token after verify of email and mobile',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forgot_password', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_comment='store jwt token after verify of email and mobile',
               existing_nullable=False)

    # ### end Alembic commands ###
