"""adjust columns

Revision ID: 30cbce404b82
Revises: 9da83b4e200d
Create Date: 2025-11-10 15:56:07.291924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30cbce404b82'
down_revision = '9da83b4e200d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_column('device_info')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('meta_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True, comment='store meta data'))
        batch_op.add_column(sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True, comment='store ip address of request device'))
        batch_op.add_column(sa.Column('device_info', mysql.VARCHAR(length=200), nullable=True, comment='store requested device info'))

    # ### end Alembic commands ###
