"""add forgot password table

Revision ID: 4ab06e515c22
Revises: e127dc3957a9
Create Date: 2025-12-02 10:04:57.976386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab06e515c22'
down_revision = 'e127dc3957a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forgot_password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='link with users table id'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='store jwt token after verify of email and mobile'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='time for expire otp'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='created time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='update time'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_forgot_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forgot_password')
    # ### end Alembic commands ###
