"""create schema

Revision ID: 9da83b4e200d
Revises: 
Create Date: 2025-11-10 15:20:59.520239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da83b4e200d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='primary key of user'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='username of the user'),
    sa.Column('email', sa.String(length=150), nullable=False, comment='email id of user'),
    sa.Column('email_verified', sa.Boolean(), nullable=True, comment='email verification boolean'),
    sa.Column('mobile', sa.String(length=15), nullable=False, comment='mobile number of user'),
    sa.Column('mobile_verified', sa.Boolean(), nullable=True, comment='mobile verification boolean'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='encrypted password of user'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='active, pending, block, delete'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='time of user created'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='time of user update'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='link with users table id'),
    sa.Column('otp', sa.String(length=6), nullable=False, comment='store otp of email and mobile'),
    sa.Column('purpose', sa.String(length=20), nullable=False, comment='register, forgot, login'),
    sa.Column('channel', sa.String(length=10), nullable=False, comment='email, sms, both'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='time for expire otp'),
    sa.Column('is_used', sa.Boolean(), nullable=True, comment='check otp is used or not boolean'),
    sa.Column('attempt_count', sa.Integer(), nullable=True, comment='how many attempt do'),
    sa.Column('resend_count', sa.Integer(), nullable=True, comment='how many time otp sent'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='store ip address of request device'),
    sa.Column('device_info', sa.String(length=200), nullable=True, comment='store requested device info'),
    sa.Column('meta_data', sa.JSON(), nullable=True, comment='store meta data'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='created time'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='update time'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_todo_user', onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    op.drop_table('otp')
    op.drop_table('users')
    # ### end Alembic commands ###
