"""alter user columns

Revision ID: d5b00d4e79b5
Revises: 30cbce404b82
Create Date: 2025-11-11 10:04:22.544135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5b00d4e79b5'
down_revision = '30cbce404b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('mobile'))
        batch_op.drop_column('mobile')
        batch_op.drop_column('mobile_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='mobile verification boolean'))
        batch_op.add_column(sa.Column('mobile', mysql.VARCHAR(length=15), nullable=False, comment='mobile number of user'))
        batch_op.create_index(batch_op.f('mobile'), ['mobile'], unique=True)

    # ### end Alembic commands ###
