"""add creted and updated column in todo table

Revision ID: e127dc3957a9
Revises: 159d0b760f64
Create Date: 2025-11-13 13:05:06.024064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e127dc3957a9'
down_revision = '159d0b760f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True, comment='time of todo created'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True, comment='time of todo update'))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='primary key of todo',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=150),
               comment='Title of todo, not null',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               comment='Description of todo',
               existing_nullable=True)
        batch_op.alter_column('completed',
               existing_type=mysql.TINYINT(display_width=1),
               comment='complete or pending status',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=1),
               comment='status for softdelete',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='This is refrence of primary key of user table',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='This is refrence of primary key of user table',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='status for softdelete',
               existing_nullable=False)
        batch_op.alter_column('completed',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='complete or pending status',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Description of todo',
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=150),
               comment=None,
               existing_comment='Title of todo, not null',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='primary key of todo',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
